//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T действие.
    /// </summary>
    // *** Start programmer edit section *** (tДействие CustomAttributes)

    // *** End programmer edit section *** (tДействие CustomAttributes)
    public enum tДействие
    {
        
        // *** Start programmer edit section *** (tДействие.Утановка CustomAttributes)

        // *** End programmer edit section *** (tДействие.Утановка CustomAttributes)
        [Caption("Утановка")]
        Утановка,
        
        // *** Start programmer edit section *** (tДействие.Изменение CustomAttributes)

        // *** End programmer edit section *** (tДействие.Изменение CustomAttributes)
        [Caption("Изменение")]
        Изменение,
    }
}
