//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опреации.
    /// </summary>
    // *** Start programmer edit section *** (Опреации CustomAttributes)

    // *** End programmer edit section *** (Опреации CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОпреацииE", new string[] {
            "Дата as \'Дата\'",
            "Действие as \'Действие\'",
            "Состояние as \'Состояние\'",
            "Оборудование as \'Оборудование\'",
            "Оборудование.Название as \'Название\'",
            "Оборудование.Сотрудник.Админ as \'Админ\'",
            "Оборудование.Сотрудник.ФИО"})]
    [View("ОпреацииL", new string[] {
            "Дата as \'Дата\'",
            "Действие as \'Действие\'",
            "Состояние as \'Состояние\'"})]
    public class Опреации : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Kursovaya1.tДействие fДействие;
        
        private IIS.Kursovaya1.tСостояние fСостояние;
        
        private IIS.Kursovaya1.Пользователь fАдмин;
        
        private IIS.Kursovaya1.Оборудование fОборудование;
        
        // *** Start programmer edit section *** (Опреации CustomMembers)

        // *** End programmer edit section *** (Опреации CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Опреации.Дата CustomAttributes)

        // *** End programmer edit section *** (Опреации.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Опреации.Дата Get start)

                // *** End programmer edit section *** (Опреации.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Опреации.Дата Get end)

                // *** End programmer edit section *** (Опреации.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опреации.Дата Set start)

                // *** End programmer edit section *** (Опреации.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Опреации.Дата Set end)

                // *** End programmer edit section *** (Опреации.Дата Set end)
            }
        }
        
        /// <summary>
        /// Действие.
        /// </summary>
        // *** Start programmer edit section *** (Опреации.Действие CustomAttributes)

        // *** End programmer edit section *** (Опреации.Действие CustomAttributes)
        public virtual IIS.Kursovaya1.tДействие Действие
        {
            get
            {
                // *** Start programmer edit section *** (Опреации.Действие Get start)

                // *** End programmer edit section *** (Опреации.Действие Get start)
                IIS.Kursovaya1.tДействие result = this.fДействие;
                // *** Start programmer edit section *** (Опреации.Действие Get end)

                // *** End programmer edit section *** (Опреации.Действие Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опреации.Действие Set start)

                // *** End programmer edit section *** (Опреации.Действие Set start)
                this.fДействие = value;
                // *** Start programmer edit section *** (Опреации.Действие Set end)

                // *** End programmer edit section *** (Опреации.Действие Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Опреации.Состояние CustomAttributes)

        // *** End programmer edit section *** (Опреации.Состояние CustomAttributes)
        public virtual IIS.Kursovaya1.tСостояние Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Опреации.Состояние Get start)

                // *** End programmer edit section *** (Опреации.Состояние Get start)
                IIS.Kursovaya1.tСостояние result = this.fСостояние;
                // *** Start programmer edit section *** (Опреации.Состояние Get end)

                // *** End programmer edit section *** (Опреации.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опреации.Состояние Set start)

                // *** End programmer edit section *** (Опреации.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Опреации.Состояние Set end)

                // *** End programmer edit section *** (Опреации.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Опреации.
        /// </summary>
        // *** Start programmer edit section *** (Опреации.Админ CustomAttributes)

        // *** End programmer edit section *** (Опреации.Админ CustomAttributes)
        [PropertyStorage(new string[] {
                "Админ"})]
        [NotNull()]
        public virtual IIS.Kursovaya1.Пользователь Админ
        {
            get
            {
                // *** Start programmer edit section *** (Опреации.Админ Get start)

                // *** End programmer edit section *** (Опреации.Админ Get start)
                IIS.Kursovaya1.Пользователь result = this.fАдмин;
                // *** Start programmer edit section *** (Опреации.Админ Get end)

                // *** End programmer edit section *** (Опреации.Админ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опреации.Админ Set start)

                // *** End programmer edit section *** (Опреации.Админ Set start)
                this.fАдмин = value;
                // *** Start programmer edit section *** (Опреации.Админ Set end)

                // *** End programmer edit section *** (Опреации.Админ Set end)
            }
        }
        
        /// <summary>
        /// Опреации.
        /// </summary>
        // *** Start programmer edit section *** (Опреации.Оборудование CustomAttributes)

        // *** End programmer edit section *** (Опреации.Оборудование CustomAttributes)
        [PropertyStorage(new string[] {
                "Оборудование"})]
        [NotNull()]
        public virtual IIS.Kursovaya1.Оборудование Оборудование
        {
            get
            {
                // *** Start programmer edit section *** (Опреации.Оборудование Get start)

                // *** End programmer edit section *** (Опреации.Оборудование Get start)
                IIS.Kursovaya1.Оборудование result = this.fОборудование;
                // *** Start programmer edit section *** (Опреации.Оборудование Get end)

                // *** End programmer edit section *** (Опреации.Оборудование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опреации.Оборудование Set start)

                // *** End programmer edit section *** (Опреации.Оборудование Set start)
                this.fОборудование = value;
                // *** Start programmer edit section *** (Опреации.Оборудование Set end)

                // *** End programmer edit section *** (Опреации.Оборудование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОпреацииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпреацииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпреацииE", typeof(IIS.Kursovaya1.Опреации));
                }
            }
            
            /// <summary>
            /// "ОпреацииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпреацииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпреацииL", typeof(IIS.Kursovaya1.Опреации));
                }
            }
        }
    }
}
